#!/bin/bash

MAJOR=$(echo $DOCKER_TAG | cut -d '.' -f 1)
MINOR=$(echo $DOCKER_TAG | cut -d '.' -f -2)

for TAG in "latest" "$MAJOR" "$MINOR"; do
  docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
  docker push $DOCKER_REPO:$TAG
done
